### ISSUE TITLE
Custom description.component.html in docker

### ISSUE THREAD

**Issue by Slevel** [Hakenadu/plantuml-editor#18]
Customizing of "description.component.html" in docker-image is very difficult without building project.

May be placed this resource in custom folder and mount this folder on docker-volumes?

**Comment by Hakenadu** [comment]
@Slevel Thank you for your feedback

You may now add the following configuration at root level in your frontend-config.json to replace the content completely.

```json
"intro": {
    "description": "<h1>custom content</h1>",
    "slideshow": {
        "showMessage": false,
        "visible": false
    }
}
```

Pull the image **hakenadu/plantuml-editor:latest** or **hakenadu/plantuml-editor:0.2.1**

**Comment by Slevel** [comment]
@Hakenadu, thx!
I can setting share button to invisible mode when I use app without webdav?

**Comment by Hakenadu** [comment]
@Slevel you should be able to achieve this by removing the "share" object from the root-level of your frontend-config.json
