### ISSUE TITLE
Compatibility with sub-folder location

### ISSUE THREAD

**Issue by Slevel** [Hakenadu/plantuml-editor#21]
Please add feature for configure sub-folder location to host.
Example: localhost/my/path/to/uml.

**Comment by Hakenadu** [comment]
Hi @Slevel you should now [(0.2.2)](https://github.com/Hakenadu/plantuml-editor/releases/tag/0.2.2) be able to add a custom context path by providing the environment variable CONTEXT_PATH_PREFIX.

The context path starts with a slash and doesn't end with one.

See [docker-compose-context-path.yml](https://github.com/Hakenadu/plantuml-editor/blob/master/build/variants/adoptopenjdk/docker-compose-context-path.yml) for an example.
