### ISSUE TITLE
Create img only, read only image url

### ISSUE THREAD

**Issue by m42e** [Hakenadu/plantuml-editor#24]
I want to have the possibility to have an url, probably a subpath, which only allows to display the graphic and the (configurable) the source of the diagram, without the possibility to create a diagram on its own. So I can share a link without revealing the editor and giving access to anyone.

If it would be a subpath one could easily be protected by Nginx, etc.

**Comment by m42e** [comment]
Or, an option to define the baseUrl for the share link. So it could be changed to a service doing the image serving.

**Comment by Hakenadu** [comment]
Hi @m42e

the feature is included in the latest release and therefore available with tag "latest" and "0.3.0".
 
I published a new version of the demo at https://plantuml.mseiche.de/ and added the documentation for the frontend-config.json in the [README.md](https://github.com/Hakenadu/plantuml-editor#example-for-plantumlmseichede).
